name: Bug Report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Important: Before Creating an Issue
        Please check if a similar issue already exists by following these steps:
        1. Search [existing issues](https://github.com/tsuyoshi-otake-system-exe-jp/otak-pomodoro/issues)
        2. Check both "Open" and "Closed" issues
        3. Search with similar keywords (e.g., "timer", "notification", "sound")

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: I have checked existing issues and confirmed no similar reports exist
          required: true
        - label: I am using the latest version of the extension
          required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Please specify your OS and version
      placeholder: "e.g., Windows 11 Pro 22H2"
    validations:
      required: true

  - type: input
    id: vscode-version
    attributes:
      label: Visual Studio Code Version
      description: Please specify your VSCode version
      placeholder: "e.g., 1.85.1"
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: Otak Pomodoro Extension Version
      description: Please specify the extension version
      placeholder: "e.g., 1.2.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Please provide a clear and detailed description of the issue
      placeholder: "e.g., Timer notifications are not working correctly"
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Please provide steps to reproduce the issue
      placeholder: |
        1. Open VSCode
        2. Start a Pomodoro session
        3. Wait for timer completion
        4. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: "e.g., Timer should notify when session ends with sound and visual notification"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: "e.g., No notification appears when timer ends"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If applicable, add VSCode Developer Tools console logs
      render: shell
    validations:
      required: false